### ISSUE TITLE
通过json文件解析不成功

### ISSUE THREAD

**Issue by skccks** [intsig-textin/parsex-sdk#9]
readme中初始化解析器部分说 也可以参考textin.com的restful api调用，通过python，curl，或者postman工具获得api的原始json文件，再通过ParseX解析json文件获得解析对象。这个官网调用方式比较难找，建议直接附上链接。另外官网的调用方式返回的是md文件，并不是json文件，尝试获取了代码里的json_data内容作为原始json文件
![企业微信截图_17250083763787](https://github.com/user-attachments/assets/7ac4077b-97f7-4809-a36a-871cfb5287e6)
下面是sdk返回的结果，只返回了markdown结果， 表格、段落、图像等信息没有
![img_v3_02e8_8893d85d-af40-4dfc-ad44-b4680aef97dg](https://github.com/user-attachments/assets/59c40264-30e8-4add-bf88-1f31fcefaed7)

**Comment by binzhang** [comment]
fix, the sample code in textin saves only markdown text
